### ISSUE TITLE
Missing quotes in the example configuration: (AWSAccountID)

### ISSUE THREAD

**Issue by awsrossw** [aws-samples/amazon-security-lake-quicksight#41]
Original:

{
   "app": "python3 app.py",
   "context": {
     "rollup_region": "<region>",
     "region": "<region>",
     "slregion": "<region>",
     "LakeFormationAdminRoleARN": "arn:aws:iam::123456789012:role/<Rolename>",
     "SecurityLakeAccountID": 123456789012,
     "AWSAccountID":555555555555,
     "QuickSightUserARN": "arn:aws:quicksight:<Region>:123456789012:user/default/<PrincipalId>"   
   }
 }

Fixed:

{
   "app": "python3 app.py",
   "context": {
     "rollup_region": "<region>",
     "region": "<region>",
     "slregion": "<region>",
     "LakeFormationAdminRoleARN": "arn:aws:iam::123456789012:role/<Rolename>",
     "SecurityLakeAccountID": 123456789012,
     "AWSAccountID": "555555555555",
     "QuickSightUserARN": "arn:aws:quicksight:<Region>:123456789012:user/default/<PrincipalId>"   
   }
 }

**Comment by adplotzk** [comment]
This issue has been resolved in most resent merge.
